### PR TITLE
 #170947596 Configure testing environment

### PR DESCRIPTION
**Pull request by T2Wil**
#### What does this PR do?
- This PR sets the testing environment.
#### Description of Task to be completed?
- configure jest framework.
- install test-react-library.
- add test script in the Readme.md.
- test a `Header` component on a landing page example.
- add `Circle CI` continuous integration tool.

#### How should this be manually tested?
- open your favourite terminal
- run `git clone https://github.com/andela/knights-bn-frontend.git` to have the repo on your local machine.
- run `cd knights-bn-frontend` to enter inside the project directory.
- run `git checkout ch-config-tests-environment-170947596` to switch to this branch.
- run `npm install` to install all dependencies required by this branch.
- run `npm start` to start the server and see the landing page example with the centred header to be tested.
- run `npm test` to run the tests.

#### Any background context you want to provide?
N/A

## Landing page example
image

## Tests result
image

#### What are the relevant pivotal tracker stories?
[Test environment story link](https://www.pivotaltracker.com/story/show/170947596)
[Continuous integration story link](https://www.pivotaltracker.com/story/show/170947597)

### CODE REVIEW

**Review by EugeneMunya — APPROVED** [review]

**Review by Niyonsengaeric — APPROVED** [review]

**Comment by Niyonsengaeric** [comment]
nice work @T2Wil

**Review by Kagorora — APPROVED** [review]
I have tested the endpoint and everything work accordingly

**Review by kagabof — CHANGES_REQUESTED** [review]
great work, In order, to create a good folder structure you should create a folder named assets where you add all your styles and images.

**Comment by T2Wil** [comment]
> great work, In order, to create a good folder structure you should create a folder named assets where you add all your styles and images.

Thanks for the comment @kagabof ,
I already have the `assets` folder, however, it only includes images.
All the `js`, `scss` and `test` files are inside the folder of their corresponding `component`

```
Below is the example of `Header` Component
```
image

I have found this folder structure simplifying finding of files that relates to a particular component and I was planning to share it to all the teammates.

Let me know if I can still move the CSS files to the `assets` folder.

**Review by kagabof — APPROVED** [review]

**Comment by kagabof** [comment]
Well done.

**Pull request merged**
